name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    uses: tryghost/actions/.github/workflows/test.yml@0cbdcbeb9030f46b109d5e6e44c14933026d8ca5 # main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
